#ifndef _CHALK_H_
#define _CHALK_H_

#define CHALK_DEFAULT_FG "\x1b[39m"
#define CHALK_DEFAULT_BG "\x1b[49m"
#define CHALK_DEFAULT_STRIKE "\x1b[29m"
#define CHALK_DEFAULT_REVEAL "\x1b[28m"
#define CHALK_DEFAULT_INVERSE "\x1b[27m"
#define CHALK_DEFAULT_BLINK "\x1b[25m"
#define CHALK_DEFAULT_UNDERLINE "\x1b[24m"
#define CHALK_DEFAULT_ITALIC "\x1b[23m"
#define CHALK_DEFAULT_INTENSITY "\x1b[22m"
#define CHALK_DEFAULT_BOLD "\x1b[21m"
#define CHALK_RESET "\x1b[0m"

#define CHALK_BLACK(FMT) "\x1b[30m" FMT CHALK_DEFAULT_FG
#define CHALK_RED(FMT) "\x1b[31m" FMT CHALK_DEFAULT_FG
#define CHALK_GREEN(FMT) "\x1b[32m" FMT CHALK_DEFAULT_FG
#define CHALK_YELLOW(FMT) "\x1b[33m" FMT CHALK_DEFAULT_FG
#define CHALK_BLUE(FMT) "\x1b[34m" FMT CHALK_DEFAULT_FG
#define CHALK_MAGENTA(FMT) "\x1b[35m" FMT CHALK_DEFAULT_FG
#define CHALK_CYAN(FMT) "\x1b[36m" FMT CHALK_DEFAULT_FG
#define CHALK_WHITE(FMT) "\x1b[37m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_BLACK(FMT) "\x1b[90m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_RED(FMT) "\x1b[91m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_GREEN(FMT) "\x1b[92m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_YELLOW(FMT) "\x1b[93m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_BLUE(FMT) "\x1b[94m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_MAGENTA(FMT) "\x1b[95m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_CYAN(FMT) "\x1b[96m" FMT CHALK_DEFAULT_FG
#define CHALK_LIGHT_WHITE(FMT) "\x1b[97m" FMT CHALK_DEFAULT_FG

#define CHALK_BG_BLACK(FMT) "\x1b[40m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_RED(FMT) "\x1b[41m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_GREEN(FMT) "\x1b[42m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_YELLOW(FMT) "\x1b[43m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_BLUE(FMT) "\x1b[44m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_MAGENTA(FMT) "\x1b[45m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_CYAN(FMT) "\x1b[46m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_WHITE(FMT) "\x1b[47m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_BLACK(FMT) "\x1b[100m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_RED(FMT) "\x1b[101m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_GREEN(FMT) "\x1b[102m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_YELLOW(FMT) "\x1b[103m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_BLUE(FMT) "\x1b[104m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_MAGENTA(FMT) "\x1b[105m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_CYAN(FMT) "\x1b[106m" FMT CHALK_DEFAULT_BG
#define CHALK_BG_LIGHT_WHITE(FMT) "\x1b[107m" FMT CHALK_DEFAULT_BG

#define CHALK_BOLD(FMT) "\x1b[1m" FMT CHALK_DEFAULT_BOLD
#define CHALK_DIM(FMT) "\x1b[2m" FMT CHALK_DEFAULT_INTENSITY
#define CHALK_ITALIC(FMT) "\x1b[3m" FMT CHALK_DEFAULT_ITALIC
#define CHALK_UNDERLINE(FMT) "\x1b[4m" FMT CHALK_DEFAULT_UNDERLINE
#define CHALK_BLINK(FMT) "\x1b[5m" FMT CHALK_DEFAULT_BLINK
#define CHALK_STRIKE(FMT) "\x1b[9m" FMT CHALK_DEFAULT_STRIKE
#define CHALK_INVERSE(FMT) "\x1b[7m" FMT CHALK_DEFAULT_INVERSE
#define CHALK_HIDE(FMT) "\x1b[8m" FMT CHALK_DEFAULT_REVEAL

#endif /* _CHALK_H_ */
